# This is a basic workflow to help you get started with Actions

name: push to photonbeam

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'main'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.PHOTONBEAM_SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.PHOTONBEAM_SSH_KNOWN_HOSTS }}
         config: ${{ secrets.PHOTONBEAM_SSH_CONFIG }}
    - run: |
        git remote add dokku dokku@photonbeam.ch:game-een
        git checkout main
        git push dokku main
